---
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-debian"
  armhf: "ghcr.io/home-assistant/armhf-base-debian"
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian"
  armv7: "ghcr.io/home-assistant/armv7-base-debian"
  i386: "ghcr.io/home-assistant/i386-base-debian"
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
