
---
name: HAPython-Arkteos
version: "0.0.1.0"
slug: hapython-arkteos
description: Python Arkteos Add-ons
url: https://github.com/al1moz/HAPython/arkteos
codenotary: notary@home-assistant.io
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
devices:
  - /dev/ttyUSB1:/dev/ttyUSB1
options:
  log_level: info
  port_usb: "/dev/ttyUSB1"
  password_mqtt: ""
schema:
  log_level: list(debug|info|warning)
  port_usb: str
  password_mqtt: password
map:
  - config:rw