
---
name: HAPython Mycron
version: "0.0.1.0"
slug: hapython-mycron
description: Python Crontab Add-ons
url: https://github.com/al1moz/HAPython/mycron
codenotary: notary@home-assistant.io
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
devices:
  - /dev/ttyUSB1:/dev/ttyUSB1
options:
  password_mqtt: ""
schema:
  password_mqtt: password
map:
  - config:rw